set(ROBOCIN_PROJECT_NAME "soccer-common")

if(NOT DEFINED ROBOCIN_PROJECT_NAME)
    message(FATAL_ERROR "ROBOCIN_PROJECT_NAME is not defined.")
endif()

set(ROBOCIN_PROJECT_PATH ${CMAKE_CURRENT_SOURCE_DIR})

set(ROBOCIN_PROJECT_VERSION_MAJOR 1)
set(ROBOCIN_PROJECT_VERSION_MINOR 5)
set(ROBOCIN_PROJECT_VERSION_PATCH 1)

set(ROBOCIN_PROJECT_VERSION ${ROBOCIN_PROJECT_VERSION_MAJOR}.${ROBOCIN_PROJECT_VERSION_MINOR}.${ROBOCIN_PROJECT_VERSION_PATCH})

add_compile_definitions(ROBOCIN_PROJECT_NAME)
add_compile_definitions(ROBOCIN_PROJECT_PATH)

add_compile_definitions(ROBOCIN_PROJECT_VERSION_MAJOR)
add_compile_definitions(ROBOCIN_PROJECT_VERSION_MINOR)
add_compile_definitions(ROBOCIN_PROJECT_VERSION_PATCH)

add_compile_definitions(ROBOCIN_PROJECT_VERSION)