set(ROBOCIN_PROJECT_NAME "soccer-common")

if(NOT DEFINED ROBOCIN_PROJECT_NAME)
    message(FATAL_ERROR "ROBOCIN_PROJECT_NAME is not defined.")
endif()

set(ROBOCIN_PROJECT_PATH ${CMAKE_CURRENT_SOURCE_DIR})

set(ROBOCIN_PROJECT_VERSION_MAJOR 1)
set(ROBOCIN_PROJECT_VERSION_MINOR 5)
set(ROBOCIN_PROJECT_VERSION_PATCH 1)

set(ROBOCIN_PROJECT_VERSION "${ROBOCIN_PROJECT_VERSION_MAJOR}.${ROBOCIN_PROJECT_VERSION_MINOR}.${ROBOCIN_PROJECT_VERSION_PATCH}")

function(ROBOCIN_LINK_PROJECT_DEFINITIONS TARGET_NAME)
    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_NAME="${ROBOCIN_PROJECT_NAME}")
    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_PATH="${ROBOCIN_PROJECT_PATH}")

    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_VERSION_MAJOR=${ROBOCIN_PROJECT_VERSION_MAJOR})
    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_VERSION_MINOR=${ROBOCIN_PROJECT_VERSION_MINOR})
    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_VERSION_PATCH=${ROBOCIN_PROJECT_VERSION_PATCH})

    target_compile_definitions(${TARGET_NAME} PRIVATE ROBOCIN_PROJECT_VERSION="${ROBOCIN_PROJECT_VERSION}")
endfunction()