name: Build CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      # Install all dependencies using setup.py script inside scripts folder
      - name: install-dependencies
        run: cd ${GITHUB_WORKSPACE}/scripts && sudo ./setup.py --essentials
      
      - name: build
        run: cd ${GITHUB_WORKSPACE} && mkdir build && cd build && cmake .. && make -j$(grep -c ^processor /proc/cpuinfo)
      
      - name: run-tests
        run: cd ${GITHUB_WORKSPACE}/bin &&
          (
            if [ -d "test/" ]; then
              for test in $(find . -executable -type f); do
                ${test} && echo " ";
              done;
            fi
          )
