name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        version: '5.14.2'

    - name: Get qmake version
      run: qmake --version
    
    - name: set repository name
      run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash

    - name: test project build
      run: cd $GITHUB_WORKSPACE/ && qmake $REPOSITORY_NAME.pro -spec linux-g++ && make qmake_all
