name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        version: '5.15.1'

    - name: Install OpenGL
      run: sudo apt-get install freeglut3 freeglut3-dev

    - name: Get qmake version
      run: qmake --version

    - name: test project build
      run: cd $GITHUB_WORKSPACE/ && qmake ${{ github.event.repository.name }}.pro -spec linux-g++ && make
